name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: dicoding_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install pg --no-save
      - name: migrate and test
        run: |
          npm install node-pg-migrate --no-save
          npx node-pg-migrate up
          npm run test
        env:
          CI: true
          HOST: localhost
          PORT: 3000
          PGHOST: forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: developer
          PGDATABASE: dicoding_app_test