name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: dicoding_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: normal migrate
        run: |
          npm install node-pg-migrate --no-save
          npm run migrate up
        env:
          CI: true
          HOST: localhost
          PORT: 3000
          PGHOST: forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: developer
          PGDATABASE: dicoding_app
          PGHOST_TEST: forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com
          PGUSER_TEST: postgres
          PGDATABASE_TEST: dicoding_app_test
          PGPASSWORD_TEST: developer
          PGPORT_TEST: 5432
          ACCESS_TOKEN_KEY: "8b7b4ef375716ab08b2a3951b29d52fc00b1c855f9d1a847229b8c5935bef56d9d271e76a9cf08e614300395c3b90ebe559cf968a0741b18c9505549394b2c70"
          REFRESH_TOKEN_KEY: "5078605e074a462b1460608fcbe0d0963c644402e04ad334455ff5a856cb43fd99825861dde02957d5e3184c90c532ca7d0249df20fe93d535632f3d11be7bad"
          ACCESS_TOKEN_AGE: 3000          
      - name: migrate and test
        run: |
          npm run migrate:test up
          npm run test
        env:
          CI: true
          HOST: localhost
          PORT: 3000
          PGHOST: forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: developer
          PGDATABASE: dicoding_app_test
          PGHOST_TEST: forum-api.cmf0aog8mvir.us-east-1.rds.amazonaws.com
          PGUSER_TEST: postgres
          PGDATABASE_TEST: dicoding_app_test
          PGPASSWORD_TEST: developer
          PGPORT_TEST: 5432
          ACCESS_TOKEN_KEY: "8b7b4ef375716ab08b2a3951b29d52fc00b1c855f9d1a847229b8c5935bef56d9d271e76a9cf08e614300395c3b90ebe559cf968a0741b18c9505549394b2c70"
          REFRESH_TOKEN_KEY: "5078605e074a462b1460608fcbe0d0963c644402e04ad334455ff5a856cb43fd99825861dde02957d5e3184c90c532ca7d0249df20fe93d535632f3d11be7bad"
          ACCESS_TOKEN_AGE: 3000          
          